name: Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies (Frontend)
      run: |
        npm install

    - name: Build frontend
      run: |
        npm run build
  

    - name: Trigger front-end redeploy
      run: |
          curl -X GET \
            https://api.render.com/deploy/srv-cqr2m4g8fa8c73fmtar0?key=Cp1R_fyjJpQ
            